name: Auto PR from SIT to Main

on:
  push:
    branches: [sit]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SIT branch
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Create PR from SIT to Main
        run: |
          # Check if a PR from sit to main already exists
          existing_pr=$(gh pr list --base main --head sit --json number --jq '.[0].number')

          if [ -z "$existing_pr" ]; then
            echo "No existing PR found. Creating a new one..."
            gh pr create \
              --title "Promote SIT to Main" \
              --body "Automatically creating a pull request from SIT to Main." \
              --base main \
              --head sit
          else
            echo "PR from sit to main already exists: #$existing_pr"
          fi
        env:
          GH_TOKEN: ${{ secrets.CICD_TOKEN }}
