name: Promote Dev to SIT

on:
  push:
    branches: [dev]

permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Print Repository Context
        run: echo "github.repository: ${{ github.repository }}"
        
      - name: Create PR from dev to sit
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          commit-message: Promote from dev to sit
          title: Promote dev to sit
          body: Auto promotion from dev to sit
          base: sit
          branch: dev
