name: Update README with PR Status

on:
  workflow_run:
    workflows: ["Auto PRs from Dev and SIT"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: read

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Update README with PR status
        run: |
          # Get open PR numbers if they exist
          dev_to_sit=$(gh pr list --base sit --head dev --state open --json number --jq '.[0].number')
          sit_to_main=$(gh pr list --base main --head sit --state open --json number --jq '.[0].number')

          # Default status
          dev_status="❌"
          sit_status="❌"

          if [ -n "$dev_to_sit" ]; then
            dev_status="✅"
          fi

          if [ -n "$sit_to_main" ]; then
            sit_status="✅"
          fi

          # Create new status block
          cat <<EOF > status_table.md
          <!-- PR-STATUS-START -->
          | Stage        | Source Branch | Target Branch | Open PR |
          |--------------|----------------|----------------|---------|
          | Dev ➝ SIT    | dev            | sit            | $dev_status |
          | SIT ➝ Main   | sit            | main           | $sit_status |
          <!-- PR-STATUS-END -->
          EOF

          # Replace section between markers
          awk '
            BEGIN {in_block=0}
            /<!-- PR-STATUS-START -->/ {print; system("cat status_table.md"); in_block=1; next}
            /<!-- PR-STATUS-END -->/ {in_block=0; next}
            !in_block {print}
          ' README.md > README.tmp && mv README.tmp README.md

          # Commit and push if there are changes
          if [[ $(git status --porcelain) ]]; then
            git add README.md
            git commit -m "Update PR status in README"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GH_TOKEN: ${{ secrets.CICD_TOKEN }}
