name: Update README with PR Status

on:
  workflow_run:
    workflows: ["Auto PRs from Dev and SIT"]  # Trigger when the first workflow completes
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Update README with PR status
        run: |
          # Check if PR exists from dev to sit
          dev_to_sit=$(gh pr list --base sit --head dev --state open --json number --jq '.[0].number')
          sit_to_main=$(gh pr list --base main --head sit --state open --json number --jq '.[0].number')

          # Set default statuses as ❌ (not found)
          dev_status="❌"
          sit_status="❌"

          # If PRs exist, update status to ✅
          if [ -n "$dev_to_sit" ]; then
            dev_status="✅"
          fi

          if [ -n "$sit_to_main" ]; then
            sit_status="✅"
          fi

          # Update the README.md file with PR status
          sed -i '/<!-- PR-STATUS-START -->/,/<!-- PR-STATUS-END -->/c\
<!-- PR-STATUS-START -->\n\
| Stage | Source Branch | Target Branch | Open PR |\n\
|-------|----------------|----------------|---------|\n\
| Dev ➝ SIT | dev | sit | '"$dev_status"' |\n\
| SIT ➝ Main | sit | main | '"$sit_status"' |\n\
<!-- PR-STATUS-END -->' README.md

          # Commit and push the changes if README.md was updated
          if [[ $(git status --porcelain) ]]; then
            git add README.md
            git commit -m "Update PR status in README"
            git push
          fi
        env:
          GH_TOKEN: ${{ secrets.CICD_TOKEN }}
